version: "3.7"

networks:
  default:

services:
  dev-php:
    build: ./docker/images/php/7.2
    volumes:
      - ./app:/var/www/html
    hostname: dev-php
    environment:
      APPLICATION_ENV: "development"
  dev-nginx:
    image: nginx
    ports:
      - "${FRONTEND_HTTP_PORT}:80"
      - "${FRONTEND_HTTPS_PORT}:443"
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
      - ./logs/nginx:/var/log/nginx
    hostname: dev-nginx
    networks:
      default:
        aliases:
          - symfony.local
  dev-postgresql:
    build: ./docker/images/db/postgresql/10
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./var/postgresql:/var/lib/postgresql
    hostname: dev-postgresql
